### ISSUE TITLE
Is the network down? 503 Error "name 'tonlib' is not defined"

### ISSUE THREAD

**Issue by ahmeteminkocal** [orbs-network/ton-gateway#38]
I am getting this error:

`{ ok: false, error: "name 'tonlib' is not defined", code: 503 }
`

**Comment by sudovag3** [comment]
i had the same error, try to use VPN

**Comment by ahmeteminkocal** [comment]
Orbs network has a problem. Moved to self hosted node.

**Comment by ahmeteminkocal** [comment]
Moved to self hosted node.
