### ISSUE TITLE
Rename parameter "suffix" to "format"

### ISSUE THREAD

**Issue by talkol** [orbs-network/ton-gateway#5]
We have a new parameter called "suffix". Let's rename it to "format". 

It will have the following current values: "default" | "json-rpc" | "rest"

- "default" means the default format for the protocol currently selected. Each protocol needs to specify its default format separately. For toncenter protocol the default format is json-rpc.

- "json-rpc" means to enforce json RPc assuming its supports by the protocol

- "rest" means to enforce rest assuming its supported by the protocol

This parameter should remain optional and its default value is "default"

I'm not sure how to pass this parameter through the URL, maybe /json-rpc or /rest or /default in the end of the URL that goes to fastly. Please let me know what you propose for the URL

**Comment by uv-orbs** [comment]
got it, no prob

**Comment by hossen71** [comment]
BKAQNT4-14A
